name: BranchCI

on:
  workflow_call:
    inputs:
      src:
        description: The folder containing the source code
        type: string
        required: true

jobs:
  light-ci:
    name: Lint & Docs ubuntu-latest Py3.11
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a
    # More info on options: https://github.com/conda-incubator/setup-miniconda
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.12"
        environment-file: devtools/conda-envs/test_env.yaml
        activate-environment: test
        auto-update-conda: false
        auto-activate-base: false
        show-channel-urls: true
    - name: Install package
      # conda setup requires this special shell
      shell: bash -l {0}
      run: |
        python -m pip install . --no-deps
        conda list
    - name: Run linters
      shell: bash -l {0}
      run: |
        black --check --diff --extend-exclude '_version.py' ${{ inputs.src }} tests
        flake8 ${{ inputs.src }} tests
    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest -v --doctest-modules --cov=${{ inputs.src }} --cov-report=term --color=yes tests/ $(MODULE)
    - name: Test documentation
      shell: bash -l {0}
      run: |
        make html
